### ISSUE TITLE
Invalid input pattern

### ISSUE THREAD

**Issue by danikalt** [dirkjanfaber/victron-vrm-api#10]
@dirkjanfaber Since Update 3days ago i have on nodes i edit following error: Invalid input pattern

![vrm_api](https://github.com/dirkjanfaber/victron-vrm-api/assets/155717655/68580974-6fac-4ef7-8438-617a071268b0)

![vrm_api1](https://github.com/dirkjanfaber/victron-vrm-api/assets/155717655/4a0d1cd2-dac7-445e-9f34-2a79895f732b)

Only if i open an exist Node and close it again it happens
What i doo wrong?

**Comment by dirkjanfaber** [comment]
I think I know what might be causing that. Let me test a few things and probably release an update afterwards.

**Comment by dirkjanfaber** [comment]
That should be fixed from version 0.1.2 (could take a few hours before Node-RED sees the new version though). 

Thanks for reporting!

**Comment by JJANOUSEK1** [comment]
hello, i have same issues

**Comment by dirkjanfaber** [comment]
@JJANOUSEK1 Your token must be 64 characters, containing just letters and numbers (as created on https://vrm.victronenergy.com/access-tokens). I think you are trying to fill out your password.

**Comment by JJANOUSEK1** [comment]
:) of course I created token in vrm  and has 64 characteres, but after deploy - no work and if i go again to the settings than i see only what i sent before (shorter stars in token fields)

![Image](https://github.com/user-attachments/assets/cb233521-75da-47ba-9fd7-842f47a3f99d)

**Comment by JJANOUSEK1** [comment]
![Image](https://github.com/user-attachments/assets/21177a47-b8b0-4da2-8dd5-6521012acbf4)

**Comment by dirkjanfaber** [comment]
I've just tested and can connect just fine. It should report the token in the 'headers' -> `X-Authorization:` on the debug tab.

![Image](https://github.com/user-attachments/assets/d913535c-b036-4c87-8e46-2c650a2263e5)

But you are right, that, going back to the properties, I also get a red bar around the _VRM token_. While that is a bit annoying, it doesn't match the problem danikalt was having. Querying the API still works.

**Comment by JJANOUSEK1** [comment]
I can't connect to vrm at all...and I have an older version.  0.2.10

**Comment by JJANOUSEK1** [comment]
connection to cerbo is ok, but vrm api not work 

![Image](https://github.com/user-attachments/assets/2907fe7e-f988-4b71-adff-8db80f83b15a)

**Comment by dirkjanfaber** [comment]
Then I think something else is wrong (which could be on the VRM side). Did some tests to check. Can you modify the flow to start at "beginning of day" instead of  "now"?

Does the debug tab show any additional info?

**Comment by JJANOUSEK1** [comment]
Today is working -  I donˇt know where was problem, but thanks for your time...
