### ISSUE TITLE
Idea: Use Variable in "VRM Site ID"

### ISSUE THREAD

**Issue by danikalt** [dirkjanfaber/victron-vrm-api#13]
May thers a possibility to also use a Variable into VRM Site ID like {{flow.siteID}}? I often copy Boards from one to another Dashboard. So if i can set a global Variable i have to set it only once:-)

![image](https://github.com/dirkjanfaber/victron-vrm-api/assets/155717655/292286bd-9dc5-4142-8424-680f1d568a80)

**Comment by dirkjanfaber** [comment]
Nice idea! I've added it to the code and created a new release.

**Comment by danikalt** [comment]
Thanks!!!!
