### ISSUE TITLE
Timespan request - tomorrow

### ISSUE THREAD

**Issue by ckupris** [dirkjanfaber/victron-vrm-api#15]
Is it possible to have a timespan option which would return the forecast for "tomorrow" similar to what is returned via the VRM web interface? Use case; during the day you want to lookup the forecast for the whole of tomorrow, not now+24hr which may cut off some of tomorrows yield depending on when you run the query.

Thanks

**Comment by dirkjanfaber** [comment]
It seems to be a bug in determining when that +24 hr ends. I hope to fix that soon (but accept pull requests if someone else feels like fixing it).

**Comment by danikalt** [comment]
i would need also "tomorrow" if theres a change to geht it - i do also often forcastcalculation in relation to desission of chargingtime

**Comment by dirkjanfaber** [comment]
@codeworkx did some of these changes before. Perhaps he has some extra time to check this.

**Comment by gizmocuz** [comment]
I would also be very happy if this was possible.
Please please please.... 😁

Would it be a matter of adding a 'bot' (beginning of tomorrow) in vrm-api.html and modify vrm-api.js to set the start of tomorrow?

If yes, I'm more than happy to make a PR for this

**Comment by dirkjanfaber** [comment]
Sure, go ahead. Probably won't be able to merge it in the next two weeks though.

**Comment by dirkjanfaber** [comment]
Sure, go ahead. Probably won't be able to merge it in the next two weeks though.

**Comment by gizmocuz** [comment]
Great, I made the PR, see

https://github.com/dirkjanfaber/victron-vrm-api/pull/23

**Comment by dirkjanfaber** [comment]
Merged it. Creating a new release soon.
