### ISSUE TITLE
API Atribute Consumption different values between 1h interval and 15min interval

### ISSUE THREAD

**Issue by danikalt** [dirkjanfaber/victron-vrm-api#16]
as i understand it right - i can call "Consumption" by 1h Interval into the Consumptionarray - it means in records.consumption 1 i see total consumtion of that h

if i compair it with 15min interval i expect that nr. 4-7 in summary must be same like in hour interval nr. 1 - or not?

![image](https://github.com/dirkjanfaber/victron-vrm-api/assets/155717655/bf8e2f9b-57da-42b3-b429-37bab41088bc)

**Comment by dirkjanfaber** [comment]
Asked around and it is known that there is some strange behaviour with 15 minutes on the API side.
For the current hour (where 15 minutes are relevant), it should work well.

There is nothing that I can change about that, apart from removing the drop down option from the node.  But I'll leave it there for now, as it still might be useful for the current hour.
