### ISSUE TITLE
Properties available parameter/values

### ISSUE THREAD

**Issue by OttmarKonrad** [dirkjanfaber/victron-vrm-api#17]
Using attribute="installations stats", attribute="Solar direct use" and Interval="years" the start field can be defined to "- 1 week" only.

This delivers the total of one week not the total of a year.

Same behavior with e.g.attribute="Solar to battery"

Would be nice to select by starting "-1 year" in this way.

Any ideas or plans?

**Comment by dirkjanfaber** [comment]
Good idea. I've added -1 year, -12 weeks and -4 weeks. And made a new release (0.2.3).

**Comment by OttmarKonrad** [comment]
Wow, that was frickin' fast and it works! =:-)
See a small difference of the values comparing to vrm dashboard. Not important but why that?
Thanks Ottmar

**Comment by dirkjanfaber** [comment]
Not sure, but it could be that VRM uses slightly different endpoints for data retrieval. If you have an example with screenshots of the settings and differences, I can take a closer look (but that might take a few days; I'll enjoy a long weekend in an hour from now. :).

**Comment by OttmarKonrad** [comment]
Thanks mate, please enjoy your weekend first and have fun! Will gather the infomation meanwhile.

**Comment by OttmarKonrad** [comment]
Hi Dirk-Jan,

as an example (other value differs in a similar way) here the value of "solar direct use" as range of 1 year:
**1 - Node Red**
![Bildschirmfoto 2024-04-21 um 23 15 58](https://github.com/dirkjanfaber/victron-vrm-api/assets/60276469/992c567e-449b-4afd-ab24-e61af9d6e41b)
**2- VRM Dashboard**
![Bildschirmfoto 2024-04-21 um 23 22 30](https://github.com/dirkjanfaber/victron-vrm-api/assets/60276469/ac298f17-4755-45e5-846e-6c576bcbc083)

Hope this helps
Ottmar

**Comment by OttmarKonrad** [comment]
Please also take an eye on my comment here:
https://github.com/dirkjanfaber/victron-vrm-api/issues/12#issuecomment-2068209724
