### ISSUE TITLE
[BUG] in url version 0.2.8

### ISSUE THREAD

**Issue by wa-kanaal** [dirkjanfaber/victron-vrm-api#26]
Using the vrm-api to fetch the current price.

Recently updated form verion 0.2.5 to 0.2.8. Since then getting following error: "Error fetching VRM data".
Looking to the url the vrm-api is sending I see difference 

These are the urls that the vrm-api's send. (Yes, I have changed the side id and token.)
{"url":"https://vrmapi.victronenergy.com/v2/installations/000000/stats?type=dynamic_ess&start=1729191600&end=1729195199","options":{},"headers":{"X-Authorization":"Token ----","accept":"application/json","User-Agent":"nrc-vrm-api/0.2.5"}}

{"url":"https://vrmapi.victronenergy.com/v2/installations/000000/stats?type=dynamic_ess?start=1729191600&end=1729195199","options":{},"headers":{"X-Authorization":"Token ----","accept":"application/json","User-Agent":"nrc-vrm-api/0.2.8"}}

I see a small difference in them. 
In versoin 0.2.5 there is a & in the this part =dynamic_ess&start= while in version 0.2.8 there is a ? in that place.
Probably this difference causes the communication error with version 0.2.8.

**Comment by dirkjanfaber** [comment]
I am able to reproduce. Will fix and release an update for it.

**Comment by dirkjanfaber** [comment]
Resolved in version 0.2.9
