### ISSUE TITLE
Custom request

### ISSUE THREAD

**Issue by haavardNO** [dirkjanfaber/victron-vrm-api#3]
@dirkjanfaber I dont get all the values I was hoping for using the "diagnostic data", since it is limited to 100. And I cant figure out how to send a spesific request with a inject node. For instance this request : `https://vrmapi.victronenergy.com/v2/installations/NNNNNNN/widgets/Status`
I am quite new to this, so sorry if this is something I should have picked up my self, byt can someone explain how to inject a custom request?

**Comment by dirkjanfaber** [comment]
Sorry for the late reply. Guess you are not that new to it anymore by now. ;) 

There is only support for the Summary State widgets in the node. Afaik a global `widgets/Status` does not exist as an API endpoint.

Closing this issue. Feel free to open a new one if you still struggle with this.
